const LOGIN_ACTION = "LOGIN";
const LOGOUT_ACTION = "LOGOUT";

const NEW_BOARD_CREATED = "NEW_BOARD_CREATED";
const BOARD_DELETED = "BOARD_DELETED";

const GET_LISTS = "GET_LISTS";
const GET_LISTS_AND_CARDS = "GET_LISTS_AND_CARDS";
const NEW_LIST_CREATED = "NEW_LISTS_CREATED";
const LIST_DELETED = "LIST_DELETED";

const NEW_CARD_CREATED = "NEW_CARD_CREATED";
const CARD_DELETED = "CARD_DELETED";
const GET_CARDS = "GET_CARDS";
const CARD_PATCHED = "CARD_PATCHED";

export {
  LIST_DELETED,
  NEW_LIST_CREATED,
  GET_LISTS,
  LOGIN_ACTION,
  LOGOUT_ACTION,
  NEW_BOARD_CREATED,
  BOARD_DELETED,
  GET_CARDS,
  GET_LISTS_AND_CARDS,
  NEW_CARD_CREATED,
  CARD_DELETED,
  CARD_PATCHED,
};
