const LOGIN_ACTION = "LOGIN";
const LOGOUT_ACTION = "LOGOUT";

const NEW_BOARD_CREATED = "NEW_BOARD_CREATED";
const BOARD_DELETED = "BOARD_DELETED";

export { LOGIN_ACTION, LOGOUT_ACTION, NEW_BOARD_CREATED, BOARD_DELETED };
