const LOGIN_ACTION = "LOGIN";
const LOGOUT_ACTION = "LOGOUT";

const NEW_BOARD_CREATED = "NEW_BOARD_CREATED";
const BOARD_DELETED = "BOARD_DELETED";

const GET_LISTS = "GET_LISTS";
const NEW_LISTS_CREATED = "NEW_LISTS_CREATED";
const LIST_DELETED = "LIST_DELETED";

export {
  LIST_DELETED,
  NEW_LISTS_CREATED,
  GET_LISTS,
  LOGIN_ACTION,
  LOGOUT_ACTION,
  NEW_BOARD_CREATED,
  BOARD_DELETED,
};
